AllCops:
  TargetRubyVersion: 2.3

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Rails:
  Enabled: true
