language: ruby
rvm:
  - 2.3.3
sudo: required
dist: trusty
addons:
  postgresql: "9.5"
env:
  - TRAVIS_NODE_VERSION="7.7.3"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install && cd client && npm install && npm run build:test
  - bundle install
before_script:
  - psql -c 'create database advocacyccommons_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
