default: &default
  swing_left_network:
    name: 'Swing Left Network'
    groups:
     - name: 'Swing Left'
    google_gsuite_key: 'lib/networks/swing_left_network/service_account.json' # TODO: PUT IN CORRECT KEY
    google_gsuite_admin_email: 'james@affinity.works' # TODO: PUT IN CORRECT ADMIN EMAIL
    google_gsuite_email_base: '@affinity.works' # TODO: PUT IN CORRECT EMAIL BASE

development:
  <<: *default

production:
  <<: *default

test:
  swing_left_network:
    name: 'Swing Left Network'
    groups:
     - name: 'Swing Left'
    google_gsuite_key: 'test/fixtures/files/service_account.json'
    google_gsuite_admin_email: 'james@affinity.works'
    google_gsuite_email_base: '@affinity.works'
  the_avengers:
    name: 'The Avengers'
    groups:
      - name: 'Fantastic Four'
